# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: OpenPDF maven deploy

on:
  release:
    types: [created]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
            java: [ 8 ]
    name: Java ${{matrix.java}}  

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set maven version to ${{ vars.GITHUB_REF }}
      run: mvn -B versions:set -DnewVersion=${{ vars.GITHUB_REF }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B clean package deploy --file pom.xml -Dmaven.resolver.transport=wagon -s $GITHUB_WORKSPACE/settings.xml --no-transfer-progress -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dgpg.skip
      env:
        GITHUB_TOKEN: ${{ github.token }}
